// GENERATED FILE — do not edit by hand.
// Source: redirects.csv. Regenerate with `pnpm seo:redirects`.
// 50 rules.

/** Old path (trailing slash stripped) -> new path. Consumed by middleware.ts. */
export const LEGACY_REDIRECTS: Readonly<Record<string, string>> = Object.freeze({
  "/product/turmeric-powder": "/product/turmeric-powder-haldi-powder",
  "/product/gift-health-this-year-for-rakhi": "/collections/combos",
  "/product-category/combo-packs": "/collections/combos",
  "/product-category/spices": "/collections/spices",
  "/product-category/teas": "/shop",
  "/product-tag/blue-tea-loose": "/product/premium-herbal-blue-tea-loose",
  "/product-tag/blue-tea-teabags": "/product/premium-herbal-blue-tea-teabags",
  "/product-tag/red-tea-loose": "/product/premium-herbal-red-tea-loose",
  "/product-tag/red-tea-teabags": "/product/premium-herbal-red-tea-teabags",
  "/product-tag/classic-tea": "/collections/classic-teas",
  "/product-tag/premium-aasam-tea": "/collections/classic-teas",
  "/product-tag/combo-packs": "/collections/combos",
  "/product-tag/spices": "/collections/spices",
  "/product-tag/powder": "/collections/spices",
  "/product-tag/black-pepper": "/product/black-pepper-powder",
  "/product-tag/coriander": "/product/coriander-powder",
  "/product-tag/garam-masala": "/product/garam-masala-powder",
  "/product-tag/red-chilly": "/product/red-chilli-powder",
  "/product-tag/turmeric": "/product/turmeric-powder-haldi-powder",
  "/product-tag/tea": "/shop",
  "/privacy-policy": "/privacy",
  "/terms-conditions": "/terms",
  "/terms-of-service": "/terms",
  "/my-account": "/account",
  "/sign-in": "/login",
  "/sign-up": "/register",
  "/wishlist": "/account/wishlist",
  "/compare": "/shop",
  "/2021/03/17/a-beginners-guide-to-understanding-the-different-types-of-spices": "/blog",
  "/2021/03/17/spices-beyond-flavor-their-role-in-medicine-and-wellness": "/blog",
  "/2021/03/17/the-magic-of-spices-how-they-elevate-your-cooking": "/blog",
  "/category/fresh-spices": "/blog",
  "/tag/food": "/blog",
  "/tag/fresh": "/blog",
  "/tag/healthy": "/blog",
  "/author/admin": "/blog",
  "/about-us": "/shop",
  "/contact-us": "/shop",
  "/faqs": "/shop",
  "/order_status": "/order/lookup",
  "/order_status/packed": "/order/lookup",
  "/order_status/shipped": "/order/lookup",
  "/order_status/in-transit": "/order/lookup",
  "/order_status/out-for-delivery": "/order/lookup",
  "/ct-mega-menu": "/",
  "/ct-mega-menu/demos": "/",
  "/ct-mega-menu/elements": "/",
  "/ct-mega-menu/shop": "/shop",
  "/footer": "/",
  "/footer/footer": "/",
});
